security:
  jwt:
    secret-key: dGllbmRhLWJpY2ljbGV0YXMtc2VjcmV0LWtleS0yMDI2LXNlbmE=
    token-expiration: 3600000

spring:
  application:
    name: Bicicletas
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:juangabriellondonoarias@gmail.com}
    password: ${MAIL_PASSWORD:ntqgxfjanjibeoqw}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true