spring:
  application:
    name: Bicicletas

  datasource:
    # Ajusta el host y puerto si es necesario; el nombre de la DB debe ser igual al que creaste
    url: jdbc:mysql://localhost:3306/tiendaBicicletas?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root        # Tu usuario de MySQL
    password:  # Tu contraseña de MySQL
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      # 'update' valida y actualiza la estructura sin borrar tus datos existentes
      ddl-auto: update
    show-sql: true        # Muestra las consultas en consola para depuración
    properties:
      hibernate:
        format_sql: true

security:
  jwt:
    # Esta es la frase "tienda-bicicletas-..."
    # (Asegúrate de poner tu clave real aquí)
    secret-key: dGllbmRhLWJpY2ljbGV0YXMtc2VjcmV0LWtleS0yMDI2LXNlbmE=
    # Expiracion: 3600000 ms = 1 hora
    token-expiration: 3600000