spring:
  datasource:
    # URL completa de tu base de datos en Railway
    url: jdbc:mysql://maglev.proxy.rlwy.net:39735/railway
    username: root
    password: wIICeKCFsCYIPQxjbVmtoigFfRMmzIDB
    driver-class-name: com.mysql.cj.jdbc.Driver

app:
  # Esta es la URL de tu frontend en Vercel para el CORS
  frontend-url: https://frontend-tienda-bicicletas.vercel.app